export const data = [
  {
    id: 1,
    first_name: "Yulma",
    last_name: "Frowd",
    email: "yfrowd0@china.com.cn",
    gender: "Male",
  },
  {
    id: 2,
    first_name: "Taddeo",
    last_name: "Climance",
    email: "tclimance1@bravesites.com",
    gender: "Male",
  },
  {
    id: 3,
    first_name: "Roseanne",
    last_name: "Shimony",
    email: "rshimony2@tripod.com",
    gender: "Bigender",
  },
  {
    id: 4,
    first_name: "Betteann",
    last_name: "Purvey",
    email: "bpurvey3@craigslist.org",
    gender: "Female",
  },
  {
    id: 5,
    first_name: "Lynn",
    last_name: "Viel",
    email: "lviel4@sfgate.com",
    gender: "Female",
  },
  {
    id: 6,
    first_name: "Sinclair",
    last_name: "Bunnell",
    email: "sbunnell5@drupal.org",
    gender: "Male",
  },
  {
    id: 7,
    first_name: "Jorry",
    last_name: "Kunert",
    email: "jkunert6@amazon.co.uk",
    gender: "Female",
  },
  {
    id: 8,
    first_name: "Gilli",
    last_name: "Rougier",
    email: "grougier7@alibaba.com",
    gender: "Female",
  },
  {
    id: 9,
    first_name: "Mayne",
    last_name: "Hebden",
    email: "mhebden8@arstechnica.com",
    gender: "Male",
  },
  {
    id: 10,
    first_name: "Maison",
    last_name: "Adamek",
    email: "madamek9@weather.com",
    gender: "Male",
  },
];
